https://www.baidu.com/s?ie=utf-8&f=8&rsv_bp=1&rsv_idx=1&tn=baidu&wd=vue-component-creator&fenlei=256&rsv_pq=fc58600800109b2a&rsv_t=d1eeXzQZyN3laLgGEyns%2Feh9t64x1RfzPRprGz7DaW%2FniORQx%2B7zNpJDsIM&rqlang=cn&rsv_enter=0&rsv_dl=tb&rsv_sug3=2&rsv_sug1=1&rsv_sug7=001&rsv_n=2&rsv_btype=i&inputT=988&rsv_sug4=1072&rsv_sug=9
